# Use NFC pads as GPIOS
CONFIG_NFCT_PINS_AS_GPIOS=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=n

# Enable ZMK Studio
# CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# CONFIG_ZMK_POINTING=n


CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Zephyr 4.1の新しいボードチェックをバイパスする
CONFIG_ZMK_BOARD_COMPAT=y