# Use NFC pads as GPIOS
CONFIG_NFCT_PINS_AS_GPIOS=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y

# Bluetooth送信電力を0（標準）に設定して消費電力を安定させる
CONFIG_BT_CTLR_TX_PWR_0=y

# 実験的な接続機能を無効化（フリーズの原因になることがあるため、一旦オフを推奨）
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=n

# ポインティングデバイス（マウス等）機能
CONFIG_ZMK_POINTING=y

# キーイベントのキューサイズを拡張（これは有効なシンボルです）
CONFIG_ZMK_KSCAN_EVENT_QUEUE_SIZE=64

CONFIG_ZMK_USB_LOGGING=y